# Generated by Django 3.1.6 on 2021-02-01 17:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='post',
            field=tinymce.models.HTMLField(default='DEFAULT VALUE'),
        ),
    ]
