# Generated by Django 3.1.5 on 2021-01-28 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ingredients', models.TextField()),
                ('procedure', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.chef')),
                ('food', models.ManyToManyField(to='recipeapp.food')),
            ],
        ),
    ]
