# Generated by Django 3.1.6 on 2021-02-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_recipe_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='food',
        ),
    ]
