# Generated by Django 3.1.5 on 2021-01-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
