# Generated by Django 3.1.5 on 2021-01-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_chef_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='food_name',
        ),
    ]
