# Generated by Django 3.1.6 on 2021-02-01 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipeapp', '0005_auto_20210201_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='food_image',
            field=models.ImageField(blank=True, default='1', upload_to='recipe/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='post',
            field=tinymce.models.HTMLField(default='1'),
        ),
    ]
