# Generated by Django 3.1.5 on 2021-02-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0007_recipe_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
