# Generated by Django 3.1.6 on 2021-02-03 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipeapp', '0008_category_image_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AddField(
            model_name='image',
            name='chef',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='food_image',
            field=models.ImageField(blank=True, default='1', upload_to='recipe/'),
        ),
        migrations.AddField(
            model_name='image',
            name='food_name',
            field=models.CharField(default='1', max_length=60),
        ),
        migrations.AddField(
            model_name='image',
            name='ingredients',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=tinymce.models.HTMLField(default='1'),
        ),
        migrations.AddField(
            model_name='image',
            name='procedure',
            field=models.TextField(default='1'),
        ),
    ]
