# Generated by Django 3.1.6 on 2021-02-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0009_auto_20210203_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='food_image',
        ),
    ]
