# Generated by Django 3.1.6 on 2021-02-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0010_remove_image_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
    ]
