# Generated by Django 3.1.6 on 2021-02-03 16:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0011_remove_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=tinymce.models.HTMLField(default='1'),
        ),
    ]
